kafka {
  input.topic = "dev.user.badge.award.request"
  broker-servers = "localhost:9092"
  zookeeper = "localhost:2181"
  groupId = "user-badge-awarding-event-group"
  failed.topic = "dev.user.badge.award.request.failed"
  failed.groupId = "user-user.badge.award.request.failed-group"
}
task {
  restart-strategy {
    attempts = 3
    delay = 10000
  }
  parallelism = 1
  consumer {
    parallelism = 1
  }
  checkpointing {
    compressed = false
    interval = 60000
    pause {
      between {
        seconds = 5
      }
    }
    timeout = 600000
  }
  badge {
      parallelism = 1
  }
}
lms-cassandra {
  host = "localhost"
  port = 9042
  sunbird {
    db = "sunbird"
    table = "user"
  }
  coursesdb = "sunbird_courses"
  externalEnrolmentTable = "user_external_enrolments"
  enrolmentTable = "user_enrolments_v2"
  badgeLookupTable = "user_badge_lookup"
}
redis {
  host = "localhost"
  port = 6378
  connection {
    max = 2
    idle.min = 1
    idle.max = 2
    minEvictableIdleTimeSeconds = 120
    timeBetweenEvictionRunsSeconds = 300
  }
  recentBadgeActivityKey = "dashboard_recent_badge_activity"
  recentBadgeActivityMaxSize = 10
}
content {
  read {
    url = "https://portal.dev.karmayogibharat.net/api/content/v1/read/"
  }
}

extcontent {
  read {
    url = "http://localhost:7001/cios/v1/content/read/"
  }
  responseKey = "content"
  extCourses = "extCourses"
  iGOTCourses = "iGOTCourses"
  issuedCertificatesKey = "issued_certificates"
  lastIssuedOnKey = "lastIssuedOn"
  badgeDetailsV1Key = "badgeDetails_v1"
  badgeEarningDateEnabledKey = "badgeEarningDateEnabled"
  badgeEarningDateTimeKey = "badgeEarningDateTime"
  issuedBadgesKey = "issued_badges"
  criteriaKey = "criteria"
  badgeIdKey = "badgeId"
  issuedOnKey = "issuedOn"
  templateUrlKey = "templateUrl"
  badgeTemplateKey = "badgeTemplate"
}

notification {
  service {
    url = "http://localhost:8082/notifications/create"
  }
  badge {
    subCategory = "AWARD_BADGES"
    subType = "UPDATE"
    enabled = true
  }
}

