kafka {
  input.topic = "user-competency-mapping-event"
  broker-servers = "localhost:9092"
  zookeeper = "localhost:2181"
  groupId = "dev-user-competency-mapping-event-group"
  failed.topic = "dev.user.competency.mapping.event.failed"
  failed.groupId = "user-competency-mapping-event-failed-group"
}
task {
  restart-strategy {
    attempts = 3
    delay = 10000
  }
  parallelism = 1
  competency.parallelism = 1
  consumer {
    parallelism = 1
  }
  checkpointing {
    compressed = false
    interval = 60000
    pause {
      between {
        seconds = 5
      }
    }
    timeout = 600000
  }
}
lms-cassandra {
  host = "localhost"
  port = 9042
  keyspace = "sunbird"
  user {
    table = "user"
    competency {
      table = "user_competency_mapping"
    }
  }
  learner {
    achievement {
      table = "learner_achievements_v2"
    }
  }
  sunbird{
  db = "sunbird"
  }
}
redis {
  host = localhost
  port = 6379
  connection {
    max = 2
    idle.min = 1
    idle.max = 2
    minEvictableIdleTimeSeconds = 120
    timeBetweenEvictionRunsSeconds = 300
  }
}
content {
  hierarchy {
    table = "content_hierarchy"
  }
  read {
    url = "https://portal.dev.karmayogibharat.net/api/content/v1/read/"
  }
  competencies = "competencies_v6"
}
certificate {
  preprocessor {
    consumer = "user-competency-mapping-event-group"
  }
}
postgres {
  host = "localhost"
  port = 5432
  database = "sunbird"
  username = "postgres"
  password = "postgres"
}
extcontent {
  read {
    url = "http://localhost:7001/cios/v1/content/read/"
  }
  responseKey = "content"
  extCourses= "extCourses"
  db = "sunbird_courses"
  table = "user_external_enrolments"
  issuedCertificatesKey = "issued_certificates"
  version = "version"
  version2Value = "v2"
  identifierKey = "identifier"
  lastIssuedOnKey = "lastIssuedOn"
  competencyAreaIdentifierKey = "competencyAreaRefId"
  competencyThemeIdentifierKey = "competencyThemeRefId"
  competencySubThemeIdentifierKey = "competencySubThemeRefId"
  acquiredContextIdKey = "acquiredContextId"
  acquiredAtKey = "acquiredAt"
  certificateIdKey = "certificateId"
  competenciesDetails="competency_details"
  achievements= "achievements"
  competencyAreaId = "competencyAreaId"
  competencyThemeId = "competencyThemeId"
  compSubThemeId = "competencySubThemeId"
  action = "action"
  contextdata = "contextdata"
  uuid = "uuid"
  uploadedDocumentUrl = "uploadedDocumentUrl"
  issuedDate = "issuedDate"
  selfAchievemt = "selfAchievement"
  update = "UPDATE "
  delete = "DELETE"
  removed = "removed"
  added = "added"
  firstTimeUserFetchLimit = 100
  courseid = "courseid"
  enrolmenttable = "user_enrolments_v2"
  status = "status"
  batchid = "batchid"
  iGOTCourses = "iGOTCourses"
  url = "url"
  externallyUploaded = "externallyUploaded"
  trueValue = "true"
  falseValue = "false"
  externalTraining = "externalTraining"
  userEntityEnrolmentsTable = "user_external_training_enrolments"
  competencyAreaIdentifier = "competencyAreaId"
  competencySubThemeId = "competencyThemeId"
  competencySubThemeId = "competencySubThemeId"

}
